[SETTINGS]
#dataset might be tacred, tacrev, re-tacred, semeval, and chemprot
dataset=chemprot
#prompt_type might be simple or rag
prompt_type=rag
#model_name might be google/flan-t5-xl, google/flan-t5-xxl, meta-llama/Llama-2-7b-hf, meta-llama/Llama-2-13b-hf, mistralai/Mistral-7B-Instruct-v0.2, or meta-llama/Meta-Llama-3-8B-Instruct
model_name=Qwen/Qwen2.5-7B-Instruct
[OUTPUT]
# change the following paths for llm and dataset
simple_prompt_path=data/chemprot/prompts/simple_test_prompts.json
rag_test_prompts_path=data/chemprot/prompts/rag_test_prompts.json
simple_prompt_responses_path=data/chemprot/responses/simple_test_responses.json
rag_test_responses_path=data/chemprot/responses/rag_test_responses.json
[EMBEDDING]
# change the following paths for dataset
input_embedding_path = data/chemprot/train.jsonl
output_embedding_path = data/chemprot/embeddings/train_emb.npy
[SIMILARITY]
# change the following paths for dataset
test_file=data/chemprot/test.jsonl
train_file=data/chemprot/train.jsonl
train_emb=data/chemprot/embeddings/train_emb.npy
test_emb=data/chemprot/embeddings/test_emb.npy
output_index=data/chemprot/similarity_results/sentence_sim_test.json
[PATH]
# change the following paths for dataset
train_data_path=data/chemprot/train.jsonl
test_data_path=data/chemprot/test.jsonl
relations_path=data/chemprot/relations.json
test_ground_truth_path=data/chemprot/test_labels.json
[RESULTS]
# change the following paths for dataset
rag_test_prompt_path=data/chemprot/results/rag_test_metric.json
simple_prompt_results_path=data/chemprot/results/simple_test_metric.json
rag_test_error_analysis_path=data/chemprot/error_analysis/rag_test_error_analysis.json
simple_prompt_error_analysis_path=data/chemprot/error_analysis/simple_test_error_analysis.json
